In [ ]:
import numpy as np

In [176]:
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
arr1 = np.arange(1,11, 1).reshape(-1,1)
arr1

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [177]:
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
arr2 = np.zeros((3,3), int)
arr2

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [194]:
print('3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення')
arr3 = np.random.randint(1, 11, (5,5))
arr3

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення


array([[10,  8,  4,  4,  8],
       [ 9,  5,  5,  1, 10],
       [ 2,  3,  6, 10,  7],
       [ 9,  3,  7,  7,  4],
       [10,  7,  9, 10,  5]])

In [193]:
print('4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
arr4 = np.random.random((4,4))
arr4

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


array([[0.00377773, 0.90016074, 0.69345715, 0.01643265],
       [0.65152811, 0.59803853, 0.67652524, 0.96833446],
       [0.61052704, 0.2314885 , 0.46613653, 0.04118722],
       [0.46988863, 0.14760264, 0.8277218 , 0.95695331]])

In [192]:
print('5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
arr51 = np.random.randint(1, 11, (5,1))
arr51

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


array([[8],
       [1],
       [6],
       [8],
       [6]])

In [38]:
print('')
arr52 = np.random.randint(1, 11, (5,1))
arr52

array([[ 8],
       [ 5],
       [ 1],
       [ 1],
       [10]])

In [39]:
arr51 + arr52

array([[13],
       [13],
       [ 4],
       [ 7],
       [19]])

In [40]:
arr51 - arr52

array([[-3],
       [ 3],
       [ 2],
       [ 5],
       [-1]])

In [41]:
arr51 * arr52

array([[40],
       [40],
       [ 3],
       [ 6],
       [90]])

In [191]:
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
arr61 = np.random.randint(1, 11, 7)
arr61

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


array([ 3,  4,  3, 10,  9,  5,  4])

In [43]:
arr62 = np.random.randint(1, 11, 7)
arr62

array([ 4, 10,  2,  9,  2, 10,  8])

In [44]:
arr61@arr62

229

In [190]:
print('7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
arr71 = np.random.randint(1, 11, (2,2))
arr71

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


array([[ 7,  3],
       [10,  5]])

In [46]:
arr72 = np.random.randint(1, 11, (2,3))
arr72

array([[6, 9, 9],
       [5, 7, 9]])

In [47]:
np.dot(arr71, arr72)

array([[47, 67, 81],
       [60, 87, 99]])

In [189]:
print('8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
arr8 = np.random.randint(1, 11, (3,3))
arr8

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


array([[ 9,  5,  3],
       [ 1,  4,  6],
       [ 3, 10,  4]])

In [50]:
np.linalg.inv(arr8)

array([[-0.56923077,  0.35384615, -0.06153846],
       [ 0.86153846, -0.29230769, -0.12307692],
       [ 0.03076923, -0.04615385,  0.13846154]])

In [188]:
print('9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
arr9 = np.random.random((4,4))
arr9

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


array([[0.67064556, 0.1938824 , 0.5229135 , 0.69577391],
       [0.70695213, 0.75331281, 0.66114039, 0.20831608],
       [0.90668757, 0.87488627, 0.54445873, 0.3170102 ],
       [0.97782247, 0.03350848, 0.53924368, 0.54688691]])

In [53]:
arr9.T

array([[0.44029982, 0.13082078, 0.96334619, 0.41636973],
       [0.10392945, 0.44444548, 0.13220377, 0.32814023],
       [0.79893292, 0.4011141 , 0.08918322, 0.03667371],
       [0.07949789, 0.29956384, 0.04611231, 0.97370511]])

In [187]:
print('10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор')
arr101 = np.random.randint(1, 11, (3,4))
arr101

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор


array([[ 8,  3,  9,  6],
       [ 7,  8, 10, 10],
       [ 5,  1,  8,  3]])

In [55]:
arr102 = np.random.randint(1, 11, 4)
arr102

array([ 3, 10,  7,  2])

In [56]:
np.dot(arr101, arr102)

array([212, 152, 130])

In [186]:
print('11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор')
arr111 = np.random.random((2,3))
arr111

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор


array([[0.19391492, 0.78536043, 0.30861449],
       [0.51982586, 0.33561801, 0.48739753]])

In [60]:
arr112 = np.random.random(3)
arr112

array([0.25999655, 0.75737591, 0.2384523 ])

In [59]:
np.dot(arr111, arr112)

array([0.74732249, 1.35802912])

In [185]:
print('12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення')
arr121 = np.random.randint(1, 11, (2,2))
arr121

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення


array([[7, 5],
       [6, 6]])

In [63]:
arr122 = np.random.randint(1, 11, (2,2))
arr122

array([[ 9,  7],
       [10,  1]])

In [64]:
arr121 * arr122

array([[18, 63],
       [40,  2]])

In [184]:
print('13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
arr131 = np.random.randint(1, 11, (2,2))
arr131

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


array([[1, 7],
       [1, 7]])

In [68]:
arr132 = np.random.randint(1, 11, (2,2))
arr132

array([[ 1, 10],
       [ 2, 10]])

In [69]:
np.dot(arr131, arr132)

array([[ 24, 140],
       [ 17,  90]])

In [183]:
print('14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці')
arr14 = np.random.randint(1, 101, (5,5))
arr14

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці


array([[ 57,  78,  11,  83,  21],
       [ 87,  28,  41,  90,  48],
       [ 78,  56,  34,   2,  25],
       [100,  66,  62,  98,  47],
       [ 64,  23,  90,  39,  88]])

In [71]:
np.sum(arr14)

1204

In [182]:
print('15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю')
arr151 = np.random.randint(1, 11, (4,4))
arr151

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю


array([[ 4,  7,  7,  4],
       [10,  7, 10,  2],
       [ 3,  9, 10,  2],
       [ 2, 10, 10,  6]])

In [73]:
arr152 = np.random.randint(1, 11, (4,4))
arr152

array([[ 6,  9,  3,  8],
       [10, 10, 10,  6],
       [ 3,  3,  6,  3],
       [ 5,  7,  3,  5]])

In [74]:
arr151 - arr152

array([[-2,  0,  4, -6],
       [-1, -3,  0,  3],
       [ 0, -1, -4,  3],
       [-3,  0,  2,  3]])

In [180]:
print('16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
arr16 = np.random.random((3,3))
arr16

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


array([[0.651915  , 0.07042642, 0.45764074],
       [0.05558806, 0.06490178, 0.82612908],
       [0.27765653, 0.49787692, 0.567096  ]])

In [81]:
np.sum(arr16, axis=1).reshape(-1, 1)

array([[1.43577747],
       [1.20679312],
       [1.35147936]])

In [179]:
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
arr17 = np.random.randint(1, 11, (3,4))
arr17

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


array([[4, 1, 2, 2],
       [7, 4, 9, 6],
       [1, 5, 6, 8]])

In [85]:
np.square(arr17)

array([[ 81,   1, 100,   9],
       [  1,  25,  81,  25],
       [  9,   1,  64,  49]])

In [178]:
print('18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
arr18 = np.random.randint(1, 11, 4)
arr18

18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


array([2, 4, 5, 3])

In [89]:
np.sqrt(arr18)

array([1.41421356, 3.16227766, 2.64575131, 2.44948974])