In [1]:
import numpy as np

In [2]:
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
arr1 = np.arange(1,11, 1).reshape(-1,1)
arr1

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [3]:
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
arr2 = np.zeros((3,3), int)
arr2

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
print('3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення')
arr3 = np.random.randint(1, 11, (5,5))
arr3

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення


array([[ 4,  6,  5,  6,  4],
       [ 9,  3,  6,  6,  1],
       [ 3,  3,  8,  3,  6],
       [ 1, 10,  8,  3,  7],
       [ 3,  2,  9,  4,  3]])

In [5]:
print('4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
arr4 = np.random.random((4,4))
arr4

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


array([[0.9625332 , 0.93663179, 0.71071109, 0.39172439],
       [0.6692826 , 0.85954403, 0.86041485, 0.78231561],
       [0.59036489, 0.37928042, 0.42772481, 0.02528362],
       [0.15641792, 0.45564854, 0.42457494, 0.30273969]])

In [6]:
print('5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
arr51 = np.random.randint(1, 11, (5,1))
arr51

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


array([[6],
       [5],
       [5],
       [1],
       [4]])

In [7]:
print('')
arr52 = np.random.randint(1, 11, (5,1))
arr52

array([[10],
       [ 5],
       [10],
       [ 4],
       [ 6]])

In [8]:
arr51 + arr52

array([[16],
       [10],
       [15],
       [ 5],
       [10]])

In [9]:
arr51 - arr52

array([[-4],
       [ 0],
       [-5],
       [-3],
       [-2]])

In [10]:
arr51 * arr52

array([[60],
       [25],
       [50],
       [ 4],
       [24]])

In [11]:
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
arr61 = np.random.randint(1, 11, 7)
arr61

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


array([2, 5, 1, 2, 6, 9, 3])

In [12]:
arr62 = np.random.randint(1, 11, 7)
arr62

array([ 5,  4,  6,  4,  2, 10,  2])

In [13]:
arr61@arr62

152

In [14]:
print('7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
arr71 = np.random.randint(1, 11, (2,2))
arr71

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.


array([[3, 3],
       [5, 5]])

In [15]:
arr72 = np.random.randint(1, 11, (2,3))
arr72

array([[8, 7, 5],
       [5, 9, 1]])

In [16]:
np.dot(arr71, arr72)

array([[39, 48, 18],
       [65, 80, 30]])

In [17]:
print('8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
arr8 = np.random.randint(1, 11, (3,3))
arr8

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.


array([[ 7,  1, 10],
       [ 1,  8,  8],
       [ 9, 10,  9]])

In [18]:
np.linalg.inv(arr8)

array([[ 0.01305057, -0.14845024,  0.11745514],
       [-0.10277325,  0.04404568,  0.07504078],
       [ 0.10114192,  0.0995106 , -0.08972268]])

In [19]:
print('9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
arr9 = np.random.random((4,4))
arr9

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


array([[0.34311823, 0.79182315, 0.22894144, 0.97533642],
       [0.27048083, 0.36584667, 0.55451915, 0.36918686],
       [0.18115095, 0.54636038, 0.01889039, 0.98707769],
       [0.15403706, 0.74250649, 0.67217389, 0.42173066]])

In [20]:
arr9.T

array([[0.34311823, 0.27048083, 0.18115095, 0.15403706],
       [0.79182315, 0.36584667, 0.54636038, 0.74250649],
       [0.22894144, 0.55451915, 0.01889039, 0.67217389],
       [0.97533642, 0.36918686, 0.98707769, 0.42173066]])

In [21]:
print('10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор')
arr101 = np.random.randint(1, 11, (3,4))
arr101

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор


array([[ 7, 10,  2, 10],
       [10,  4, 10,  7],
       [ 4,  8,  3,  8]])

In [22]:
arr102 = np.random.randint(1, 11, 4)
arr102

array([ 8, 10,  3,  7])

In [23]:
np.dot(arr101, arr102)

array([232, 199, 177])

In [24]:
print('11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор')
arr111 = np.random.random((2,3))
arr111

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор


array([[0.91452981, 0.57334862, 0.72742987],
       [0.07114151, 0.61170798, 0.82707243]])

In [25]:
arr112 = np.random.random(3)
arr112

array([0.68784462, 0.37525137, 0.96079671])

In [26]:
np.dot(arr111, arr112)

array([1.54311649, 1.07312703])

In [27]:
print('12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення')
arr121 = np.random.randint(1, 11, (2,2))
arr121

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення


array([[7, 1],
       [4, 5]])

In [28]:
arr122 = np.random.randint(1, 11, (2,2))
arr122

array([[7, 3],
       [3, 1]])

In [29]:
arr121 * arr122

array([[49,  3],
       [12,  5]])

In [30]:
print('13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
arr131 = np.random.randint(1, 11, (2,2))
arr131

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


array([[3, 2],
       [4, 7]])

In [31]:
arr132 = np.random.randint(1, 11, (2,2))
arr132

array([[10,  7],
       [10,  3]])

In [32]:
np.dot(arr131, arr132)

array([[ 50,  27],
       [110,  49]])

In [33]:
print('14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці')
arr14 = np.random.randint(1, 101, (5,5))
arr14

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці


array([[74, 62, 63, 88, 14],
       [ 4, 39, 50, 29, 55],
       [60, 14, 84, 19, 31],
       [ 5, 66, 10, 79, 32],
       [43, 51, 94, 96, 81]])

In [34]:
np.sum(arr14)

1243

In [35]:
print('15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю')
arr151 = np.random.randint(1, 11, (4,4))
arr151

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю


array([[ 8,  3, 10,  8],
       [ 5, 10,  7,  3],
       [ 3,  5,  2,  7],
       [ 6,  1,  1,  3]])

In [36]:
arr152 = np.random.randint(1, 11, (4,4))
arr152

array([[ 5,  9,  3,  3],
       [ 7,  9,  6,  7],
       [ 1,  9,  1, 10],
       [ 3,  8,  7,  9]])

In [37]:
arr151 - arr152

array([[ 3, -6,  7,  5],
       [-2,  1,  1, -4],
       [ 2, -4,  1, -3],
       [ 3, -7, -6, -6]])

In [38]:
print('16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
arr16 = np.random.random((3,3))
arr16

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


array([[0.13692507, 0.65101235, 0.01228054],
       [0.01236641, 0.93731434, 0.21560017],
       [0.66394044, 0.5773005 , 0.8529131 ]])

In [39]:
np.sum(arr16, axis=1).reshape(-1, 1)

array([[0.80021795],
       [1.16528092],
       [2.09415405]])

In [40]:
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
arr17 = np.random.randint(1, 11, (3,4))
arr17

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


array([[10,  5, 10, 10],
       [ 3,  8,  2,  6],
       [ 7, 10, 10,  4]])

In [41]:
np.square(arr17)

array([[100,  25, 100, 100],
       [  9,  64,   4,  36],
       [ 49, 100, 100,  16]])

In [42]:
print('18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
arr18 = np.random.randint(1, 11, 4)
arr18

18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


array([1, 9, 6, 5])

In [43]:
np.sqrt(arr18)

array([1.        , 3.        , 2.44948974, 2.23606798])